title: Pedro Nogueira
theme: minima
plugins:
  - jekyll-multiple-languages-plugin

languages:
  - en
  - pt
  - es

# Define as configurações do idioma padrão
default_locale: en
collections:
  publications:
    output: true
    permalink: /portfolio/:title/
