title: Pedro Nogueira
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  publications:
    output: true
    permalink: /publications/:path/
  posts:
    output: true
    permalink: /posts/:path/

languages:
  - en
  - pt
  - es

defaults:
  - scope:
      path: ""  # Aplica o idioma padrão globalmente
    values:
      lang: "en"  # Define o idioma padrão como inglês

exclude_from_localizations:
  - assets
  - js
  - images
  - favicon.ico

i18n_dir: "_i18n"  # Direciona o Jekyll para os arquivos de tradução


future: true
