# default_lang: en
baseurl: ""
title: Pedro Nogueira
languages: ["en", "pt", "es"]


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin
  - jekyll-last-modified-at

collections:
  codes:
    output: true
    # permalink: /:lang/codes/:slug/
  publications:
    output: true
    permalink: /:lang/publications/:slug/
  blogposts:
    output: true
    permalink: /:lang/blog/:slug/

# defaults:
#   - scope:
#       path: "_blogposts/en"
#       type: blogposts
#     values:
#       lang: en
#       permalink: /en/blog/:slug/

exclude_from_localizations:
  - assets
  - css
  - _blogposts
  - _codes
  - _publications
i18n_dir: "_i18n" # Direciona o Jekyll para os arquivos de tradução
default_locale_in_subfolder: true

future: true
# Permalink settings
